Working version of Arbitrable abstract contract
ethercourt/workspace pull request #2
Opened 2016-12-15 00:40 UTC by clesaege

+ small arbitrable contract which only modify its state

2016-12-15 11:22 UTC, n1c01a5 requested changes

2016-12-15 11:22 UTC, n1c01a5 commented on decentralized-court/contracts/Arbitrated/Arbitrated.sol
> -     *  TO DO: Verify that we can't abuse of with the appeal mechanism.
maybe `TODO`

2016-12-15 11:22 UTC, n1c01a5 commented on decentralized-court/contracts/Arbitrated/Arbitrated.sol
>          if (_disputeID!=disputeID) // There were no dispute
Add `.` to finish the comment sentence.

2016-12-16 00:07 UTC, clesaege commented on decentralized-court/contracts/Arbitrated/Arbitrated.sol
>          if (_disputeID!=disputeID) // There were no dispute
Change to "Not arbitrating the current dispute.".

2016-12-16 00:07 UTC, clesaege commented on decentralized-court/contracts/Arbitrated/Arbitrated.sol
> -     *  TO DO: Verify that we can't abuse of with the appeal mechanism.
OK

2016-12-16 23:55 UTC, closed without merging